### ISSUE TITLE
Add tag in the json when using BIDS

### ISSUE THREAD

**Issue by manuegrx** [populse/mri_conv#12]
Hi,

When we used a project already in BIDS to import data using mri_conv, information contained in the BIDS json are not added to the new json created by mri_conv (for example repetionTime, EchoTime ...) .

It could be nice to have them, in order, for example, to automatically fill the database when importing data in MIA> 

Is this possible ? Let me know if I can help in any way 

Emmanuelle

**Comment by montigno** [comment]
Hi,

If I understand correctly, we would like to manually add some parameters like RepetitionTime, EchoTime in the json ?.... Where do BIDS come from? Can we find these parameters in the BIDS structure ?

You will come see me when you can.

Olivier

**Comment by montigno** [comment]
Hi,

A new version of mri_conv is available (23.4.0a). 

Please keep me informed.

Olivier

**Comment by manuegrx** [comment]
Hi, 

It works, thank you ! 

Emmanuelle
