### ISSUE TITLE
Not the good unit in json for time metadata when importaing data in BIDS

### ISSUE THREAD

**Issue by manuegrx** [populse/mri_conv#19]
Hi, 

When data are imported from BIDS format there is an issue in the time unit in the mri_conv json. 

In the BIDS json, time metadata as repetition time or echo time are given in seconds whereas in the mri_conv json the units is ms. 
However, the value from BIDS json is used in the mri_conv json without any conversion. 

Is it possible to add the conversion of the seconds in milliseconds ? 
Here is an example of the json in mri_conv and in BIDS :
 [mri_conv.json](https://github.com/user-attachments/files/16364023/mri_conv.json) 

[bids.json](https://github.com/user-attachments/files/16364028/bids.json)

Emmanuelle

**Comment by montigno** [comment]
Hi @manuegrx,

You will find in the 'devpt' branch, a new version of mri_conv (24.3.1b).

Now, Repetition Time, Echo Time and Inversion Time are in milliseconds.
If there are other parameters to put in ms, let me know.


Olivier

**Comment by manuegrx** [comment]
It is all good thank you ! 

Emmanuelle
