### ISSUE TITLE
Populse_mia crashed during the import

### ISSUE THREAD

**Issue by blemasso** [populse/mri_conv#2]
I have some trouble to import Bruker data into MIA.
An issue, which explain the bug, is already open in populse_mia
   https://github.com/populse/populse_mia/issues/80

you can find the dataset used to reproduce the bug here:
   https://filesender.renater.fr/?s=download&token=38b80e02-a32f-27c3-5732-6a7aa9dec256

**Comment by montigno** [comment]
I may have an explanation, see my comment on this issue 
populse/populse_mia#80

**Comment by montigno** [comment]
Problem resolved. see populse/populse_mia#80
