### ISSUE TITLE
Repetition Time as 4th resolution

### ISSUE THREAD

**Issue by montigno** [populse/mri_conv#20]
Hi @manuegrx,

In the new version(24.3.1b), Nifti now has Repetition Time value as 4th resolution (This only concerns 4D and 5D images).

Can you check if this works?

Thanks !

Olivier

**Comment by manuegrx** [comment]
Yes it works ! 

Before : 
 Voxel size:        2.5 x 2.5 x 2.54528 x 0
 
 
 After 
   Voxel size:        2.5 x 2.5 x 2.54528 x 3
