### ISSUE TITLE
Import NIfTI/json , json format 

### ISSUE THREAD

**Issue by manuegrx** [populse/mri_conv#21]
Hi, 

I would like to use mri_conv to import NIfTI/json (not organized in BIDS ). 

When I export the data (via the basket), the json is copied as is and therefore does not have the same format as the others json files exported by mri_conv ( [json IRMaGe](https://populse.github.io/mri_conv/Irmagejson/irmagejson.html)).
For Populse mia it is an issue but maybe it is not an issue for others uses. 

As in the DictionnaryMRI_System.yml there is indications for "whereNifti", I thought it will create a json with the same format as usual (and with the tag recognised by  "whereNifti") . 

Emmanuelle

**Comment by montigno** [comment]
Hi Emmanuelle,

I will be able to look at this issue this week.

For now, mri_conv does not rebuild json when exporting from NifTi to NifTi, it only duplicates.

Where do your raw Nifti come from? 
Maybe I can add in the yaml dictionary another indication than 'whereNifti' (whereNiftiDicom2niix for example).

Olivier

**Comment by manuegrx** [comment]
Hi, 

I have several cases, the raw NIfTI and JSON can come from dcm2niix  or it can be also a NIfTI from a pipeline and with a json "handmade". In this last case I thought  that if I used the same json tag in my json "handmade" as written for "whereNifti" (the keyName) in the DictionnaryMRI_System.yml, it could create a new json (with the json IRMaGe format)

**Comment by montigno** [comment]
Hi,

In the Dcm2niix json, there is a tag "ConversionSoftware", this could help me to know the origin of the conversion. In your "handmade" json, do you have the possibility to add this tag? and specify its value?

**Comment by manuegrx** [comment]
Yes I can add this tag !

**Comment by montigno** [comment]
In the Dcmi2niix json, we have "ConversionSoftware": "dcm2niix".
What value do you want to set?

**Comment by manuegrx** [comment]
What you want ! I do not have a precise idea, I think it should be quite generic. 

Quick question , why it is not possible to use the  'whereNifti' that is already in the DictionnaryMRI_System.yml ?

**Comment by montigno** [comment]
Hi Emmanuelle,

I pushed a new version to the dvpt branch.

Now we can export the Nifti/Json from dcm2niix.
For the "handmade" ones, you need to add "ConversionSoftware: handmade" in your json.

I did some tests on some files, I think you will do more tests, you will tell me if you encounter any problems.

Olivier

**Comment by manuegrx** [comment]
Hi, 

Sorry for the late answer ! 
It is working well for dcm2niix json and for handmade json, thank you
