### ISSUE TITLE
Return Code, when mri_conv is closed by user.

### ISSUE THREAD

**Issue by servoz** [populse/mri_conv#3]
Currently, if the user closes the mri_conv without importing data, the return code is not 0 (in linux 1).
It might be interesting that in this case, mia catch a particular return code (say -100, but to discuss).
Because right now, Mia is handling this case as if there was a problem with mri_conv

**Comment by montigno** [comment]
Yes, it's possible to set '100' as return code (without the '-' character, otherwise this would generate a random number).
To confirm and i will change this in the next version.

**Comment by servoz** [comment]
100 is fine for me !

**Comment by servoz** [comment]
It's seems to work fine ! Thanks
