### ISSUE TITLE
Not all data are transferred to the basket.

### ISSUE THREAD

**Issue by servoz** [populse/mri_conv#5]
Rather than a long speech, can you try to convert [the 6 scans into this directory](https://mycore.core-cloud.net/index.php/s/GF431ukTRG4WzxL). The behavior is very strange (in my case, only two scans are transferred to the basket). Do you observe the same behavior with these data ?

**Comment by montigno** [comment]
The problem came from the fact that subjects had the same Serial Number, same Protocol Name, same Acquisition Date etc...
The problem is now (in principle) fixed. To test now.

**Comment by servoz** [comment]
Thanks, I will check it ASAP !

**Comment by servoz** [comment]
Tested and validated  :thumbsup:
I close the ticket !

**Comment by montigno** [comment]
Good ! :clap:
