### ISSUE TITLE
Philips PAR/REC can't be of the format foo.par and foo.rec

### ISSUE THREAD

**Issue by servoz** [populse/mri_conv#6]
mri_conv only accepts the .PAR and .REC extension for Philips data. This may seem like an unnecessary constraint. Would it be possible to accept PAR/REC and par/rec?

**Comment by montigno** [comment]
mri_conv worked well with PAR/REC and par/rec,  but not with par/REC and PAR/rec (when one is in lower case and the other in upper case).
The bug is now fixed (i hope so), and the latest version is currently in the 'devt' branch.

**Comment by servoz** [comment]
Thanks @montigno devpt branch works indeed fine with .par/.rec. I close this ticket !!!!
